#' This is a function to import data from the CSV-like output generated by Ubitrail.
#' @param FILE A string indicating the path to the input file.
#' @return A list of matrices. Each element refers to a single
#' area. Each row in the matrices represent a read (\emph{i.e.} an 
#' information about the tracked agent at a given time);
#' @examples
#' myResult <- rubitRead(file) # this can be slow for large data
#' summary(myResult) # show the number of read for each area
#' head(myResult[[1]]) # show the first reads of the first area
#' Do NOT try to print large data:
#' rubitRead(file) ##do NOT do that
#' @note By design, Ubitrail needs to learn to discriminate the agent from the background.
#' This is performed individualy for each area. Although this is usually fast and negligible, 
#' in some conditions (\emph{i.e.} if the agent is static or hides) it can take some time.
#' For a given area, no reads will be stored if the experiment is interupted before the individual model is trained.
#' \emph{It is therefore perfectly possible to obtain a list missing some areas}.
#' In most cases, thiss can be interpreted as an immobile behaviour.
#' @seealso \code{\link{rubitGlobal}} for getting general information
#' @keywords input
#' @export
rubitRead <- function(FILE){

	d<-read.table(FILE,sep=",", head = TRUE, skip = 1,quote ="",comment.char="",colClasses=c("character","integer","numeric","numeric","numeric","numeric"))
	#d <- sqldf("select * from FILE", dbname = tempfile(), file.format = list(header = T, row.names = F,skip = 1))
	# Gets the ROIs identity
	rois <- sort(unique(d$Area));
	# Creates a list "l" 1 element per ROI. The first colums is removed because it contains redondant info 
	l<-lapply(rois,
		function(r){
		    return(as.matrix(d[d$Area %in% r,-which(colnames(d)=="Area")]))
		    }
		)
	# Gives to each element of the list the name of the related ROI
	names(l)<-rois;
	# returns the list
	return(l);
}
NULL

#' This is a function to display global information about a result file.
#' @param FILE A string indicating the path to the input file.
#' @return A two-element list. The fields in the first elements are explicit. The second element is a matrix describing the position and size of all present areas.
#' @examples
#' rubitGlobal(file) # show info about this file
#' rubitGlobal(file)$Global # global informations
#' rubitGlobal(file)$Areas # infos about the areas
#' @seealso \code{\link{rubitRead}} to import the row data;
#' @keywords input
#' @export
rubitGlobal <- function(FILE){
	#	reads and parse to a global matrix
		l <- eval(
		parse(
		    text = scan(FILE,n=1,what = "character",quiet = TRUE)
		    )
		)
	return(l);
}

NULL
