NULL
#' Read data from a result file.
#' 
#' This function is used to get all the information
#' contained in a result file generated by Ubitrail into an R object.
#' @param FILE the name of the file which the metadata are to be read from.
#' @value A list of two elements. The first element contains a vector of strings corresponding to
#' global informations such as the width and heigth of the video and the date.
#' The second element contains a matrix in wich each column correspond to an area and four row to
#' describe their respective position and dimentions.
#' @note The meta-data is in the first line of the CSV file.  It is preformated as an R expression. Therefore, 
#' if you want to analyse data with another toolkit than R, you need to write a function to parse the meta data.
#' @examples
#' \dontrun{
#' l <- ubitLoadFile('Results.csv') 
#' attributes(l)
#' summary(l)
#' }
#' @seealso \code{\link{ubitMetaData}} to get only meta data from a CSV-like result file and \code{\link{ubitData}} to get only data from a CSV-like result file as a matrix. 
#' @export
ubitLoadFile <- function(FILE,verbose=FALSE){
	if(verbose) print("Reading data...")#Reading data from result file
	meta <- ubitMetaData(FILE)
	data <- ubitData(FILE)
	if(verbose) print("Formating data...")#Formating data to a list of matrix and setting attributes
	l<-ubitParseDataToList(data,meta)
	if(verbose) print("Converting data to absole data...") #Conversion to absolute data
	
	#To preserve the attributes of l:
	atrs <- attributes(l);
	l<-lapply(l,h_ubitRelativeToAbsolute,HG = as.numeric(attributes(l)[['Height']]) )
	attributes(l) <- atrs
	
	l
	}

NULL
#' Get meta-data from a result file.
#' 
#' This function is used to get general
#' informations about a CSV-like result file generated by Ubitrail.
#' @param FILE the name of the file which the metadata are to be read from.
#' @return A list of two elements. The first element contains a vector of strings corresponding to
#' global informations such as the width and heigth of the video and the date.
#' The second element contains a matrix in wich each column correspond to an area and four row to
#' describe their respective position and dimentions.
#' @note The meta-data is in the first line of the CSV file.  It is preformated as an R expression. Therefore, 
#' if you want to analyse data with another toolkit than R, you need to write a function to parse the meta-data.
#' @examples
#' \dontrun{
#' me <- ubitMetaData('Results.csv') 
#' me
#' }
#' @seealso \code{\link{ubitData}} to get only data from a CSV-like result file as a matrix.
#' @seealso \code{\link{ubitLoad}} to read a result file into a list of areas (more convenient).
#' @export
ubitMetaData <- function(FILE){
    e<-scan(FILE,what='character',nline=1)
    meta<-eval(parse(text=e))
    
    H <- as.numeric(meta$Global['Height']) 
    meta$Areas['Y',] <- H - meta$Areas['Y',]
    return(meta)
}
	
NULL
#' Get data from a result file.
#' 
#' This function is used to read data from
#' a CSV-like result file generated by Ubitrail.
#' @param FILE the name of the file which the data are to be read from.
#' @return A numerical matrix.
#' @note The returned matrix has a different variable in each column and each row is a `read'.
#' A read is written by Ubitrail every time an agent is detected. Therefore, a read contains information
#' about area, territory, position and time.
#'  
#' @examples
#' \dontrun{
#' da <- ubitData('Results.csv') 
#' summary(da)
#' }
#' @seealso \code{\link{ubitMetaData}} to get only meta data from a CSV-like result file.
#' @seealso \code{\link{ubitLoadFile}} to read a result file into a list of areas (more convenient).
#' @export
ubitData<- function(FILE){
    n<-scan(FILE,what='character',skip=1,sep=',',nlines=1)
    a<-scan(FILE,skip=2,sep=',')
    nc<-length(n)
    nr<-length(a)/nc
    m_<-matrix(a,nr,nc,byrow=T)
    colnames(m_)<-n
    return(m_)
}
NULL
#' Parse data matrix to a list of matrices.
#' 
#' This function is used to combine metadata and data into a list of matrices.
#' @param data a matrix of numerical data.
#' @param meta a list of metadata.
#' @return A list of numerical matrices.
#' @note The returned list contains a numerical marix for each area.
#' The attributes of list contain metadata.
#' Each matrix in the list is given attributes about the area it represents.
#' 
#' @examples
#' \dontrun{
#' da <- ubitData('Results.csv') 
#' me <- ubitMetaData('Results.csv') 
#' l <- ubitParseDataToList(da,me)
#' attributes(l)
#' }
#' @seealso \code{\link{ubitMetaData}} to get only meta data from a CSV-like result file.
#' @seealso \code{\link{ubitData}} to get only data from a CSV-like result file as a matrix.
#' @seealso \code{\link{ubitLoadFile}} to read a result file into a list of areas (more convenient).
#' @export
ubitParseDataToList <- function(data,meta){
	Global <- meta$Global
	Areas <- meta$Areas
	
	Areas
	l <- lapply(colnames(Areas),h_ubitSetAttributes,m=data,areas = Areas)
	names(l) <- colnames(meta$Areas)
    attributes(l) <- c(attributes(l),as.list(Global))
    l
	}

